### ISSUE TITLE
Programación orientada a eventos y Event Loop

### ISSUE THREAD

**Issue by andreslozadamosto** [banodejs/charlas#10]
**Título:** Programación orientada a eventos y Event Loop
**Twitter:** alfathenus
**Descripción:** ¿Que es la programación orientada a eventos? Historia, conceptos y donde se la utiliza. Ejemplos cotidianos y en la vida. Ejemplos técnicos. Los eventos y Javascript. Los eventos y el browser. Los eventos y Node. Event Loop, historia y conceptos. Event Loop en NodeJS. Event Loop en ejemplos cotidianos. Programando pensando en el Event Loop. NextTick().
**Tiempo:** 40 minutos

La idea de esta charla es por un lado comprender el paradigma orientado a eventos, reconocerlo en todos los ámbitos del software, entender que su entendimiento es igual de necesario que el OOP ya que es omnipresente en cualquier software de todo tipo desarrollado en la actualidad.
Por otro lado comprender los conceptos de su implementación con el algoritmo de Event Loop, como se implementa en su forma mas básica y como lo implementa NodeJS (en la libreria LibUV). Además, como sacarle provecho para mejorar nuestros programas.

Espero que les guste la idea y por favor, aporten con ideas o cosas para ir armando la presentación.

**Comment by a0viedo** [comment]
@alfathenus excelente idea! creo que es muy importante hablar de los conceptos que sirven de base a todas las aplicaciones que estamos haciendo con node. :+1:

**Comment by eafelix** [comment]
+1

**Comment by Camilolwi** [comment]
+1 !

**Comment by pfmescher** [comment]
+1

**Comment by Camilolwi** [comment]
+1 !

**Comment by andreslozadamosto** [comment]
Buenas!
Perdón por la demora en preparar la charla. La verdad que la tuve que colgar estas ultimas semanas por diferentes motivos, pero desde ya que no esta olvidada. La podría tener para fines de septiembre recién.

Saludos! =)

**Comment by a0viedo** [comment]
Charlé con @alfathenus acerca de dar la charla en Septiembre y está complicado con los tiempos. Te parece Octubre?

**Comment by mcampo** [comment]
+1

**Comment by figui** [comment]
+1
