### ISSUE TITLE
Propuesta: Socket.IO avanzado (o no tanto)

### ISSUE THREAD

**Issue by gabmontes** [banodejs/charlas#11]
Título: Socket.IO avanzado
Twitter: @gab_montes
Descripción: Describir rápidamente la comunicación bidireccional cliente-servidor, Socket.IO y algunos usos un poco más avanzados que los ejemplos típicos que se pueden encontrar en el sitio o cualquier tutorial de por ahí.
Tiempo: 20 a 30 minutos
Referencias: [socket.io](http://socket.io)

**Comment by a0viedo** [comment]
Mi voto es :+1: me parece que podría sumar mucho ver un esbozo del protocolo websockets en general, cómo encaja en eso Socket.IO, fallbacks y una idea de hasta dónde llega el soporte de Socket.IO con respecto a dispositivos móviles y diferentes versiones de los browsers.

**Comment by eafelix** [comment]
+1

**Comment by andreslozadamosto** [comment]
+1
También me gustaría, si hay tiempo, la integración otras techs, por ejemplo que la parte cliente sea cualquier otra tech (Android, IOS, Python) para mostrar que Socket.IO no solo se puede usar con un cliente javascript y que se puede ampliar su rango a mas que un chat (ejemplo clásico)

**Comment by pr0duc3r** [comment]
+1 y +1 a @alfathenus

**Comment by gvilarino** [comment]
:+1: @gabmontes es capo de la vida

**Comment by gabmontes** [comment]
Van las direcciones de la presentación de ayer y del código de la demo:
https://slides.com/gabrielmontes/socketio-avanzado
https://github.com/gabmontes/realtime-polls-demo

@a0viedo pasá luego fotos y video!
