### ISSUE TITLE
Propuesta de charla: Node under the hood

### ISSUE THREAD

**Issue by a0viedo** [banodejs/charlas#12]
**Oradores**: Lars Jacob y Diego Sanchez
**Charla**: Se va a estar viendo una introducción a cómo Node.js está construido, qué elementos lo componen y cómo interactuan entre si comenzando con las capas superiores hasta llegar a implementaciones específicas en distintos sistemas operativos (con foco en FreeBSD y Linux en general).

**Comment by a0viedo** [comment]
Les dejo links relacionados a la charla:
- Slides (en breve)
- [Fork usado en la charla](https://github.com/jaclar/io.js/tree/banode)
- [libuv](https://www.youtube.com/watch?v=nGn60vDSxQ4) por Bert Belder - charla
- [Diving into io.js C++ internals](https://youtu.be/2I_hWYHE6Vc?list=PLFZ5NyC0xHDaaTy6tY9p0C0jd_rRRl5Zm) por Fedor Indutny - charla
- [An introduction to libuv](http://nikhilm.github.io/uvbook/index.html) - libro

Si me olvido de alguno, ustedes tienen otro para sugerir o tienen alguna consulta me avisan :)

**Comment by andreslozadamosto** [comment]
Tuvo que haber estado genial esta charla, una cagada q no pude ir.... espero los slides :) 
Consulta: con respecto a luv y su funcionamiento, hasta q profundidad hablaron? porque justo en la charla que estaba preparando sobre programacion en eventos estaba por agregar como libuv maneja el event loop y esas cosas.

**Comment by adrixvoid** [comment]
Muchas gracias por los links!

**Comment by jaclar** [comment]
acá van los slides: https://github.com/jaclar/node-under-the-hood

**Comment by andreslozadamosto** [comment]
Gracias!
