### ISSUE TITLE
Propuesta de charla: Mobile Testing with Appium on nodejs

### ISSUE THREAD

**Issue by vrunoa** [banodejs/charlas#13]
Les consulto si les interesa un charla o workshop sobre Appium. La idea seria hacer algo simple, instalar appium, y correr 4, 5 ejemplos de tests sobre apps nativas e híbridas en ios y android. Integrarlos con mocha, y Sauce Labs.

**Comment by andreslozadamosto** [comment]
+1

**Comment by a0viedo** [comment]
@vrunoa qué formato preferís? workshop o charla? en caso de que sea una charla, cuanto tiempo duraría?

**Comment by vrunoa** [comment]
Me parece que workshop seria mejor. Dar una pequeña introducción sobre Appium, y después trabajar sobre ejemplos. Con una hora me parece que estaría bien, usar 10min para explicar brevemente Appium, y 50 min para mostrar y testear ejemplos. 
Les parece ?

**Comment by ariel-rios-movile** [comment]
+1
No se si es válido aún :P

**Comment by vrunoa** [comment]
@ariel-rios-movile se hizo un workshop en la NodeConf sobre Appium. Te paso las slides y el repositorio
http://slides.com/vrunoa/mobile-testing-with-appium-the-workshop#/
https://github.com/vrunoa/appium-workshop
