### ISSUE TITLE
4.0 is the new 1.0

### ISSUE THREAD

**Issue by ajchambeaud** [banodejs/charlas#14]
Finalmente abandonamos el eterno "cero punto algo" y pasamos al mundo de los grandes. Y de qué manera! saltamos directamente a la versión 4.0! Esto puede resultar confuso para los principiantes y para todos aquellos que no hallan seguido la novela io.js...

Propongo una charla explicativa sobre esta nueva versión, que incluya los siguientes topics:

-Breve historia y contexto
-Node.js Foundation
-Release project
-V8 4.5 y ES2015 (Qué hay de nuevo en JS en esta nueva versión)

Saludos!

**Comment by a0viedo** [comment]
@ajchambeaud excelente idea! cuánto tiempo calculás que puede durar la charla?

edit: y mi última pregunta, cómo te ves para darla el Jueves 17 de Septiembre?

**Comment by ajchambeaud** [comment]
Una media hora estaría bien, como para dar lugar a alguna otra charla. Me gusta el formato de dos charlas cortas. Creo que puedo prepararla para el jueves que viene!
