### ISSUE TITLE
Domótica con Node.js y RasperryPi

### ISSUE THREAD

**Issue by mcampo** [banodejs/charlas#16]
Descripción: Contruir tu propio sistema de domótica es más fácil que nunca con el reciente soporte oficial para ARM agregado en Node 4.x.
En esta charla vamos a ver ver cómo contruir una central para cualquier dispositivo de domótica que se puedan imaginar. Todo lo que se necesita es un RasperryPi y un poco de Node.js.
Se vá a mostrar una arquitectura basada en un hub central que dialoga con múltiples dispositivos más pequeños (como dispositivos basados en arduino), todo accedido de forma segura desde una interfaz web deployada en la nube.

Duración: 30 minutos. Pordría armar la charla de 20 minutos + 10 minutos para un demo en vivo.

Twitter: @tobillocrocante

**Comment by a0viedo** [comment]
Esta charla se dió en formato taller en Enero. @mcampo podrías linkear el repo y los slides para que quede? Gracias!

Si hay más gente interesada podríamos considerar repetir el taller.

**Comment by mcampo** [comment]
Link al repo que usamos en el taller: https://github.com/mcampo/workshop-domotica
Los slides que mostré brevemente: https://docs.google.com/presentation/d/1OkN2vUFd0Sruz-W5kjcehxH83VzjwpI3d2L1L0fpEPA/edit?usp=sharing
