### ISSUE TITLE
Migración de node 0.10.x a 4.2.x LTS en produccion

### ISSUE THREAD

**Issue by jaclar** [banodejs/charlas#17]
Como todos los desarolladores de node en [I am at](https://github.com/iamat/) no nos queríamos dejar atrás con las viejas versiones de node. Entonces migramos a 4.2.x. La charla va a explicar el proceso de la migración, problemas encontrados y resultados prácticos de la migración.

**Comment by jaclar** [comment]
Dado que el tema ya es medio viejo propongo el siguiente cambio:

### Migración de node 0.10.x a 4.x.x LTS en produccion

Como todos los desarolladores de node en @iamat no nos queríamos dejar atrás con las viejas versiones de node. Entonces migramos a 4.x.x. La charla va a explicar el proceso de la migración, problemas encontrados, resultados prácticos de la migración y las herramientas usadas para monitorear el estatus de la plataforma antes y después.

**Comment by a0viedo** [comment]
@jaclar tenemos slides para la charla? Gracias!

**Comment by jaclar** [comment]
Ahi van: https://github.com/jaclar/banode-node-migration-0.10
