### ISSUE TITLE
BookshelfJS ORM & KnexJS with PostgresSQL & MSSQL

### ISSUE THREAD

**Issue by gmcdowell** [banodejs/charlas#20]
Hi,

My name is Greg McDowell. I'm a Mobile SaaS founder from New Zealand. I'll be visiting Buenos Aires in late June through until mid July.

I'm proposing to discuss how we used, and decided upon, BookshelfJS and it's dependant library KnexJS in building the API that supports our Mobile Application.

I'm also currently working on contract in a business and we have used Bookshelf/Knex to connect to an SQL Server database (currently undocumented support).

We are still confirming our travel dates, however will be in BA between 25th June and 15th July, with a stint in Lima for a week or 10 days during.

**Comment by a0viedo** [comment]
[Slides](http://www.slideshare.net/GregMcDowell1/bookshelf-js-buenos-aires-nodejs-meetup-jul-2016)
[Repo de la demo](https://github.com/gmcdowell/bookshelf-demo)
