### ISSUE TITLE
Podemos reducir la utilización de if/switch en nuestro código utilizando el paradigma POO?

### ISSUE THREAD

**Issue by diegosanchez** [banodejs/charlas#21]
A raíz de charlas que tuvimos con @jaclar surgió el tema de reducir los if/switch que tenemos en nuestro código. Nos preguntamos en su momento si valía el esfuerzo o no.  En este contexto surge esta charla.  

Nos propusimos entonces un workshop en el cual se plantee una problemática (pequeña a modeo de [Code Kata](http://www.codekatas.org/)) para analizar distintas alternativas a la hora de eliminar los switch/if utilizando el paradigma de programación orientada a objetos.

**Comment by gabmontes** [comment]
@diegosanchez @a0viedo esta charla ya la dieron, correcto? Habría que cerrar el issue...

**Comment by diegosanchez** [comment]
Sip. Bien ahí! Cerras vos?

**Comment by gabmontes** [comment]
No tengo botoncito "Close"... :(

Hay video? Si hay estaría genial agregar el link a la conversación.

**Comment by diegosanchez** [comment]
Hay ppt, ahí agrego link

**Comment by diegosanchez** [comment]
Link al ppt: [http://www.slideshare.net/secret/7weKWyXmKbaAO4](http://www.slideshare.net/secret/7weKWyXmKbaAO4)

**Comment by a0viedo** [comment]
@diegosanchez gracias!

@gabmontes ya deberías poder darle close

**Comment by gabmontes** [comment]
Ahora sí!!
