### ISSUE TITLE
Propuesta de charla: Haciendo aplicaciones desktop con nwjs

### ISSUE THREAD

**Issue by hugoruscitti** [banodejs/charlas#5]
- **Titulo**: Haciendo aplicaciones desktop con nwjs
- **twitter**: @hugoruscitti
- **Descripción**:  El objetivo de la charla es ofrecer una breve reseña de
  nwjs, un proyecto de software que combina io.js junto a
  chromium para hacer aplicaciones desktop.
- **Modalidad**: La modalidad de la charla es práctica, mostrando como
  integrar emberjs a una aplicación sencilla y mostrando algunas llamadas
  a las API de io.js.
- **Orador:** Hugo Ruscitti
- **Tiempo:** 20 minutos.
- **Video charla similar:** https://www.youtube.com/watch?v=TzDhzayO_uk

**Links de referencia:**
- http://examplelab.com.ar/ (blog del orador)
- http://nwjs.io/
- http://emberjs.com/

**Comment by a0viedo** [comment]
Muy bueno @hugoruscitti! Mi opinión es +1. Y el resto? @banodejs/owners @banodejs/miembros /miembros

**Comment by eafelix** [comment]
De una , me re copo la idea! +1

**Comment by AquiGorka** [comment]
Yo ya tengo algo que podría mostrar!

De 1 I am in.

Abrax

**Comment by diegosanchez** [comment]
Genial! 
:+1:

**Comment by mgtitimoli** [comment]
Genial @hugoruscitti!! 
@AquiGorka pasate si queres lo q tenes asi lo chusmeamos...

**Comment by AquiGorka** [comment]
Github AquiGorka Remote Device ;)

**Comment by eafelix** [comment]
@hugoruscitti si queres sumate a la charla en la planificacion en 
https://github.com/banode/organizadores/issues/8

**Comment by marcoschicote** [comment]
+1

**Comment by a0viedo** [comment]
voy a poner en cc a los chicos que dieron el workshop de node-webkit (en su momento) de la [JSConfAR 2014](https://www.jsconfar.com/workshops/)

@RobertoGonzalez @sbehrends @vrunoa

**Comment by vrunoa** [comment]
Les paso el link al github del workwhop que se dio en la JSConfAr,
[https://github.com/Aerolab/jsconf2014-workshop](https://github.com/Aerolab/jsconf2014-workshop) 

Y el link a las [slides](https://github.com/Aerolab/jsconf2014-workshop/blob/master/Node-Webkit-Workshop.pdf?raw=true)

**Comment by sbaglieri** [comment]
copado!

**Comment by a0viedo** [comment]
@hugoruscitti contás con disponibilidad para el martes 31 de marzo a las 19hs?

**Comment by sbehrends** [comment]
Como dijo @vrunoa, ahi tienen el source del curso. Si quieren puedo comentarles lo que notamos que se podria mejorar de ese workshop.
En 20 minutos como planea @hugoruscitti nose cuanto se pueda llegar a cumplir de todo lo que planifican.
Lo que quieran pueden contar conmigo :)

**Comment by a0viedo** [comment]
@sbehrends gracias por pasarte! es más charla que curso, sacando la parte de hands-on. aún así si ncesitás más tiempo puede evaluar @hugoruscitti

**Comment by hugoruscitti** [comment]
@a0viedo ese martes justo voy a estar volviendo de viaje, se me va a complicar estar ahí ... ¿hay otra fecha alternativa? (de ser posible que no sea martes), de última me sumo a la próxima meetup, no hay drama...

**Comment by sbehrends** [comment]
Si es charla para mostrar posibilidades y ejemplos esta bien :+1:

**Comment by RobertoGonzalez** [comment]
@hugoruscitti Si estás buscando ejemplos, una de las cosas que más llamaron la atención es la posibilidad de levantar web servers -o cosas puramente de backend-. En el workshop de JSConf hicimos una webapp entera con Express + Socket.io (que en retrospectiva fue overkill), pero permitió mostrar muchas aristas de nw.js.

Fuera de eso, y más para una charla, vale la pena mostrar que hay apps live que usan nw.js, como Popcorn Time, Light Table, Game Dev Tycoon, etc, que destacan que la plataforma es madura y vale la pena tenerla en cuenta para desktop apps.

**Comment by a0viedo** [comment]
te parece entonces que la pasemos para el meetup de abril @hugoruscitti? contás con disponibilidad para el martes 28 de abril 19hs?

**Comment by hugoruscitti** [comment]
dale @a0viedo , me parece mucho mejor en abril. ¿Será siempre los martes?, ¿aún hay chances de que de sea otro día?, los martes son complicados para mí y los chicos del trabajo... si fuera en otro día nos cae mejor.

**Comment by a0viedo** [comment]
@hugoruscitti podriamos cambiar que sea los martes. qué otro día de la semana podrías, exceptuando miércoles y jueves cómo se menciona en https://github.com/banodejs/miembros/issues/7?

**Comment by vrunoa** [comment]
@a0viedo si va a haber live streaming avisen. Me sumo a la charla a distancia.

**Comment by a0viedo** [comment]
@vrunoa la gente de la fundación telefónica nos dijo que había que solicitar el streaming con anticipación :(

muy buena la charla @hugoruscitti! encima veníamos con el horario justo y cerraste en perfecta sincronía. si tenés un link a los slides los subimos a meetup y twitter

**Comment by hugoruscitti** [comment]
Si, la pasé super bien, me gustó mucho el ambiente, las personas super
copadas y el espacio estuvo muy bueno también :)

acá están los slides:

https://speakerdeck.com/hugoruscitti/haciendo-aplicaciones-desktop-con-nwjs

mi twitter:

@hugoruscitti

Y mi blog:

http://www.examplelab.com.ar

**Comment by vrunoa** [comment]
:+1:
