### ISSUE TITLE
Propuesta de charla: Testing, mocha, chai e istanbul

### ISSUE THREAD

**Issue by gabmontes** [banodejs/charlas#6]
**Título**: Testing, mocha, chai e istanbul
**Twitter**: @gab_montes
**Descripción**: Si bien el título es bastante descriptivo, se me ocurre hacer una breve introducción en términos prácticos al mundo del testing (menospreciado por una buena parte de los desarrolladores) para pasar de lleno a utilizar mocha (test framework), chai e istanbul sobre un pequeño proyecto.
Tiempo: 20 a 30 minutos
**Referencias**: [mochajs.org](http://mochajs.org), [chaijs.com](http://chaijs.com), [gotwarlost/istanbul](https://gotwarlost.github.io/istanbul)

**Comment by a0viedo** [comment]
groso @gabmontes! :+1: a la charla

**Comment by andreslozadamosto** [comment]
Me gusta la idea de esa charla

**Comment by sbaglieri** [comment]
suena interesante!

**Comment by a0viedo** [comment]
@gabmontes contás con disponibilidad para el martes 31 de marzo a las 19hs?

**Comment by gabmontes** [comment]
@a0viedo deberíamos cerrar este issue. ¿Qué opinás?

**Comment by a0viedo** [comment]
si, hagamos lo mismo con las charlas pasadas.
