### ISSUE TITLE
Propuesta de charla:GruntJS

### ISSUE THREAD

**Issue by andreslozadamosto** [banodejs/charlas#7]
Título: GruntJS
Twitter: @alfathenus
Descripción: La idea es presentar Grunt no solo como una herramienta de automatizacion de tareas sino tb como nos puede ayudar en el proceso de desarrollo al juntarlo con otras librerias para mantener buenas practicas de desarrollo (chequeo estatico de codigo, auto beatifull del codigo, ejecucion de tests cada vez q se guarda el archivo, etc) y para generar un entorno de deployment personalizado.
Tiempo: 20 a 30 minutos

Bueno, espero q les guste la idea. Tengo la presentacion bastante avanzada ya que brinde una charla similar en las primeras reuniones del meetup de js.

**Comment by a0viedo** [comment]
nos viniste al pelo @alfathenus! cómo te ves dando esta charla el 31 de marzo? :)

**Comment by andreslozadamosto** [comment]
Buenas!
Si, no creo tener problemas, pero las charlas ya no estaban definidas para ese meetup?

**Comment by a0viedo** [comment]
definimos la fecha del meetup pero una de los oradores no podía ese día https://github.com/banodejs/charlas/issues/5. podemos pasar esa directamente para el próximo meetup, y si te parece confirmamos esta para el 31 de marzo 19hs

**Comment by eafelix** [comment]
Genial la propuesta @alfathenus , particularmente me gusta este tema despues de usar ant y maven en mi viejo mundo Java jajajajajja. 

Lo mismo que @a0viedo , genial la propuesta y la iniciativa!

**Comment by andreslozadamosto** [comment]
Listo, confirmo la charla para ese dia.

Para terminar de armar la charla, diganme si quieren que veamos algun tema en particular de Grunt o algun ejemplo hecho en ANT/Maven/MSBuild/etc q quieran ver como se podria hacer en Grunt? Que cosas les gustaria automatizar que ahora realizan de manera manual en su dia a dia?

Gracias!

**Comment by a0viedo** [comment]
buenas @alfathenus, estamos pensando en correr la fecha del meetup por el paro nacional que se anunció para el 31. vos podrías el martes 7 de abril?

**Comment by andreslozadamosto** [comment]
Dale, si me parece lo mejor, el paro nos va a complicar a todos
