### ISSUE TITLE
Propuesta de panel: io.js

### ISSUE THREAD

**Issue by a0viedo** [banodejs/charlas#8]
**Título**: io.js 
**Twitter**: a0viedo
**Descripción**: ¿Qué es io.js? ¿Cómo nace? ¿En qué se diferencia? ¿Quienes son parte? ¿Qué planes hay a corto y largo plazo?¿Lo puedo poner en producción? ¿Quienes lo usan? ¿Es más rápido/lento? ¿Qué rol cumple la Fundación Node.js en todo esto? ¿Cómo contribuyo? Voy a estar respondiendo todas estas preguntas y con suerte muchas otras más que les puedan llegar a surgir.
**Tiempo**: 20 a 30 minutos

**Comment by andreslozadamosto** [comment]
Muy buena charla!

**Comment by gabmontes** [comment]
Estaría muy buena, sobre todo para ponernos al día con las últimas novedades de io.js y el futuro de Node.JS vs. io.js.

**Comment by vrunoa** [comment]
+1

**Comment by juanpiwi** [comment]
Me parece interesante, sobre todo me gustaría conocer las ventajas y desventajas de seguir usando una u otra plataforma

**Comment by eafelix** [comment]
Deberíamos cerrar esta charla ya que io.js se unió a la Node.js Fundation.
Podríamos conseguir una que comente el estado actual de dicha fundación.

**Comment by Camilolwi** [comment]
+1 Me uno a full!!

**Comment by andreslozadamosto** [comment]
+1
Tal como dice @eafelix una charla que explique el estado, objetivos y roadmap y que aporta io.js a Node (q segun lo que lei, la idea es que el prox release de node se base en el repositorio de io.js con alguna compatibilidad a node 0.12)

**Comment by a0viedo** [comment]
Novedades sobre la charla: el [TC de io.js decidió a favor del merge con la Node Fundation](https://www.youtube.com/watch?v=UbYiFLf7MpU). los contribuidores de joyent/node ahora se unirán al grupo ya establecido de iojs.
Más allá de estos temas, ya que muchas cosas continuarán como funcionaban en iojs, la mayoría de las preguntas siguen siendo relevantes.

**Comment by a0viedo** [comment]
Creo que con la charla https://github.com/banodejs/charlas/issues/14 y el release de Node v4 ya perdió un poco de relevancia. Cierro.
